name: uzimacare-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.1
      - asttokens==3.0.1
      - boto3==1.42.41
      - botocore==1.42.41
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - databricks-api==0.9.0
      - databricks-cli==0.18.0
      - dataclasses==0.6
      - decorator==5.2.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastapi==0.115.0
      - h11==0.16.0
      - idna==3.11
      - ipython==8.38.0
      - jedi==0.19.2
      - jmespath==1.1.0
      - johnsnowlabs==6.2.0
      - matplotlib-inline==0.2.1
      - nlu==5.4.1
      - numpy==2.2.6
      - oauthlib==3.3.1
      - packaging
      - pandas==2.3.3
      - parso==0.8.5
      - prompt_toolkit==3.0.52
      - pure_eval==0.2.3
      - py4j==0.10.9.7
      - pyarrow==23.0.0
      - pydantic==2.9.2
      - pydantic_core==2.23.4
      - Pygments==2.19.2
      - PyJWT==2.11.0
      - pyspark==3.4.0
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.22
      - pytz==2025.2
      - requests==2.32.5
      - s3transfer==0.16.0
      - six==1.17.0
      - spark-nlp==6.2.0
      - spark-nlp-display==5.0
      - stack-data==0.6.3
      - starlette==0.38.6
      - svgwrite==1.4
      - tabulate==0.9.0
      - traitlets==5.14.3
      - typing-inspection==0.4.2
      - typing_extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.3
      - uvicorn==0.30.6
      - wcwidth==0.5.3
